application: airbuddyrepo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.app
- url: /templates/css
  static_dir: templates/css
- url: /templates/images
  static_dir: templates/images
- url: /static/assets/css
  static_dir: static/assets/css
- url: /favicon.ico
  static_dir: static/images
  
libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "latest"
- name: numpy
  version: "latest"
- name: ssl
  version: "latest"