application: airbuddyrepo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  
- url: /favicon.ico
  static_dir: static/images
  
libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "latest"
- name: numpy
  version: "latest"
- name: ssl
  version: "latest"