application: airbuddyrepo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.app
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "latest"
- name: numpy
  version: "latest"
- name: ssl
  version: "latest"